apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echosrv-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "echosrvip"
    ingress.gcp.kubernetes.io/pre-shared-cert: "cf-cert"
spec:
  rules:
    - host: "echosrv.synd.io"
      http:
        paths:
          - path: /*
            backend:
              serviceName: echosrv
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: echosrv
  labels:
    app: echosrv
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: echosrv
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echosrv
  labels:
    app: echosrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: echosrv
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echosrv
    spec:
      containers:
        - name: echosrv
          image: kpurdon/echosrv:latest
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: FallbackToLogsOnError
          env:
            - name: HTTP_PORT
              value: "8001"
          ports:
            - name: http
              containerPort: 8001
